### ISSUE TITLE
Travis CI Integration

### ISSUE THREAD

**Issue by indiv0** [PistonDevelopers/blog.piston.rs#10]
If we integrate Travis CI, we can run tasks on the code (such as ensuring the output is valid HTML), which could reduce the chance of a breaking bug making it into the site.

**Comment by bvssvni** [comment]
That would be nice!

**Comment by indiv0** [comment]
Alright I'll get started on that.

**Comment by indiv0** [comment]
@bvssvni I don't have admin access on Travis CI. Could you please enable Travis CI for this repo?

**Comment by bvssvni** [comment]
Travis CI is enabled. It should be triggered on the next commit.
