### ISSUE TITLE
Delete Master Branch

### ISSUE THREAD

**Issue by indiv0** [PistonDevelopers/blog.piston.rs#12]
If all pull requests are being done against gh-pages, perhaps we could delete the master branch altogether to avoid confusion and clutter?

**Comment by leonkunert** [comment]
It is already gone. I deleted it 6 hours ago to avoid confusion. I also changed the readme to reflect this change and point to gh-pages for PRs

**Comment by indiv0** [comment]
Ah. My bad. I saw the README change and assumed master was still around :P
