### ISSUE TITLE
[POST] Initial Blog Post

### ISSUE THREAD

**Issue by indiv0** [PistonDevelopers/blog.piston.rs#4]
The blog needs an introductory blog post to introduce the project.

I can write a short, initial draft, PR it, then once merged, others can contribute until the post is ready to be published.

**Comment by indiv0** [comment]
Closed by PR #5.

**Comment by indiv0** [comment]
Actually I'll leave this open until the draft is ready to be published.

**Comment by indiv0** [comment]
@bvssvni could you take a look and add anything else you want to see in the intro post?

**Comment by bvssvni** [comment]
@Indiv0 Looks fine!

**Comment by indiv0** [comment]
@leonkunert would you or anyone else like to make any changes before we publish the post?

**Comment by leonkunert** [comment]
I like it, so I think it can be posted.
