### ISSUE TITLE
Policy for self merging: Faster iterations

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/blog.piston.rs#43]
Right now all maintainers are busy working to get stuff done. I would like to make it easier to make posts by cutting down the amount of waiting for review, because it slows down the progress.
- Posts that summary work or something being done can be self merged
- Anyone that discover a spelling error can send pull requests and merge themselves

We use the issue tracker for planning, discussion and problem solving. The blog is for things that we wish to inform the public about.

**Comment by indiv0** [comment]
I agree with the points proposed.

People shouldn't have to wait to fix obvious spelling mistakes and summarizing work doesn't need a full peer review process.
