### ISSUE TITLE
Blog theme update

### ISSUE THREAD

**Issue by rolandasb** [PistonDevelopers/blog.piston.rs#57]
I updated blog theme with the same style as a new website theme. Preview here: http://piston-blog.devlab.me/

**Comment by bvssvni** [comment]
This is lovely. You are awesome!

**Comment by rolandasb** [comment]
Is there anything you want me to change? Or should I make a pull request? :)

**Comment by bvssvni** [comment]
@rbrs Please make a PR. There is nothing I want to change.
